; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
; Add FIRMWARE_HASH to all executables regardless of usage
build_flags = 
    -include include/common/firmware_hash.h
    -Wl,--undefined=FIRMWARE_HASH
build_src_flags =
    -Wall -Wextra -Werror=return-type
extra_scripts = 
    post:scripts/firmware_hash.py
; Overrides -Og and removes debugging symbols
; Otherwise builds are not deterministic and results in OS-dependent hashes
debug_build_flags = -Os

; Freeze package versions
platform_packages =
    ;
    ; AVR
    ;
    framework-arduino-avr @ 5.1.0
    framework-arduino-avr-minicore @ 2.1.3
    tool-avrdude @ 1.60300.200527
    toolchain-atmelavr @ 1.70300.191015
    
    ;
    ; STM32
    ;
    framework-stm32cubef0 @ 1.11.3
    tool-dfuutil @ 1.11.0
    tool-ldscripts-ststm32 @ 0.2.0
    tool-openocd @ 2.1100.211028
    ; Only available on windows -- breaks CI if uncommented
    ; tool-stm32duino @ 1.0.2
    toolchain-gccarmnoneeabi @ 1.70201.0

[debug]
build_type = debug
build_flags = 
    ${env.build_flags}
    -D BB_DEBUG ; Expose BB_DEBUG define to source code

[release]
build_type = release

;
;   Device configurations
;

[ATmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

[ATmega328p]
platform = atmelavr
board = nanoatmega328new
framework = arduino

[STM32F042K6]
platform = ststm32
board = generic_f042k6
framework = stm32cube

[STM32F407VE]
platform = ststm32
board = generic_f407ve
framework = stm32cube

;
;   Thrusters Board 
;

[Thrusters]
extends = ATmega328p
build_src_filter = 
    +<Thrusters/>
    +<common/>
monitor_speed = 115200

[env:Thrusters_debug]
extends = Thrusters, debug

[env:Thrusters_release]
extends = Thrusters, release

;
;   Telem Board
;

[Telem]
extends = ATmega2560
build_src_filter = 
    +<Telem/>
    +<common/>
monitor_speed = 115200

[env:Telem_debug]
extends = Telem, debug

[env:Telem_release]
extends = Telem, release

;
;   MHPB Board
;

[MHPB]
extends = ATmega2560
build_src_filter = 
    +<MHPB/>
    +<common/>
monitor_speed = 115200

[env:MHPB_debug]
extends = MHPB, debug

[env:MHPB_release]
extends = MHPB, release

;
;   Logic Board
;

[Logic]
extends = STM32F042K6
build_src_filter = 
    +<Logic/>
    +<common/>
monitor_speed = 115200
monitor_filters = 
	time

[env:Logic_debug]
extends = Logic, debug

[env:Logic_release]
extends = Logic, release

;
;   POPB Board
;

[POPB]
extends = ATmega328p
build_src_filter = 
    +<POPB/>
    +<common/>
monitor_speed = 115200

[env:POPB_debug]
extends = POPB, debug

[env:POPB_release]
extends = POPB, release


;
;   Actuation Board
;

[Actuation]
extends = STM32F407VE
build_src_filter = 
    +<Actuation/>
    +<common/>
monitor_speed = 115200

[env:Actuation_debug]
extends = Actuation, debug

[env:Actuation_release]
extends = Actuation, release
